---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bench-results
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # Uncomment and adjust below if you want the results PVC to be created with
  # a specific storage class.
  # storageClassName: my-storage-class
