---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: storage-bench
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: storage-bench-edit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: storage-bench
  # TODO: fixup here if you want to run the benchmark in a namespace other than "default"
  namespace: default
